version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
